import type { Bus } from "./bus";

/**
 * Sharp SM83 CPU — full instruction set (roadmap step 2).
 *
 * All 256 base + 256 CB-prefixed opcodes, with flag semantics and T-cycle
 * counts from the gbops table. The opcode map is highly regular, so most of
 * the dispatch table is generated by loops; irregular opcodes are explicit.
 *
 * Interrupt dispatch, EI delay, and HALT wake are implemented; the HALT bug
 * and cycle-exact memory access timing are deferred (step 3 / accuracy work).
 */

const FZ = 0x80;
const FN = 0x40;
const FH = 0x20;
const FC = 0x10;

type OpHandler = (c: CPU) => number;

export class CPU {
  // 8-bit registers (post-boot-ROM DMG state). F only holds its top 4 bits.
  a = 0x01; f = 0xb0; b = 0x00; c = 0x13;
  d = 0x00; e = 0xd8; h = 0x01; l = 0x4d;
  sp = 0xfffe;
  pc = 0x0100;
  ime = false;
  imeScheduled = false; // EI enables IME after the *next* instruction
  halted = false;

  constructor(readonly bus: Bus) {}

  // ---- register pairs ---------------------------------------------------

  get af(): number { return (this.a << 8) | this.f; }
  set af(v: number) { this.a = (v >>> 8) & 0xff; this.f = v & 0xf0; }
  get bc(): number { return (this.b << 8) | this.c; }
  set bc(v: number) { this.b = (v >>> 8) & 0xff; this.c = v & 0xff; }
  get de(): number { return (this.d << 8) | this.e; }
  set de(v: number) { this.d = (v >>> 8) & 0xff; this.e = v & 0xff; }
  get hl(): number { return (this.h << 8) | this.l; }
  set hl(v: number) { this.h = (v >>> 8) & 0xff; this.l = v & 0xff; }

  /** Carry flag as 0/1, for ADC/SBC/RL/RR. */
  get cy(): number { return (this.f & FC) >>> 4; }

  // ---- memory helpers ---------------------------------------------------

  fetch8(): number {
    const v = this.bus.read8(this.pc);
    this.pc = (this.pc + 1) & 0xffff;
    return v;
  }

  fetch16(): number {
    return this.fetch8() | (this.fetch8() << 8);
  }

  push16(v: number): void {
    this.sp = (this.sp - 2) & 0xffff;
    this.bus.write16(this.sp, v);
  }

  pop16(): number {
    const v = this.bus.read16(this.sp);
    this.sp = (this.sp + 2) & 0xffff;
    return v;
  }

  // ---- flag helpers -----------------------------------------------------

  fl(z: boolean, n: boolean, hf: boolean, cf: boolean): void {
    this.f = (z ? FZ : 0) | (n ? FN : 0) | (hf ? FH : 0) | (cf ? FC : 0);
  }

  /** Set Z/N/H, preserve C (INC, DEC, BIT). */
  flZNH(z: boolean, n: boolean, hf: boolean): void {
    this.f = (this.f & FC) | (z ? FZ : 0) | (n ? FN : 0) | (hf ? FH : 0);
  }

  // ---- ALU --------------------------------------------------------------

  add8(v: number, carry: number): void {
    const r = this.a + v + carry;
    this.fl((r & 0xff) === 0, false, (this.a & 0xf) + (v & 0xf) + carry > 0xf, r > 0xff);
    this.a = r & 0xff;
  }

  sub8(v: number, borrow: number): void {
    const r = this.a - v - borrow;
    this.fl((r & 0xff) === 0, true, (this.a & 0xf) - (v & 0xf) - borrow < 0, r < 0);
    this.a = r & 0xff;
  }

  cp8(v: number): void {
    const r = this.a - v;
    this.fl((r & 0xff) === 0, true, (this.a & 0xf) - (v & 0xf) < 0, r < 0);
  }

  and8(v: number): void { this.a &= v; this.fl(this.a === 0, false, true, false); }
  xor8(v: number): void { this.a ^= v; this.fl(this.a === 0, false, false, false); }
  or8(v: number): void { this.a |= v; this.fl(this.a === 0, false, false, false); }

  inc8(v: number): number {
    const r = (v + 1) & 0xff;
    this.flZNH(r === 0, false, (v & 0xf) === 0xf);
    return r;
  }

  dec8(v: number): number {
    const r = (v - 1) & 0xff;
    this.flZNH(r === 0, true, (v & 0xf) === 0);
    return r;
  }

  addHL(v: number): void {
    const hl = this.hl;
    const r = hl + v;
    this.f = (this.f & FZ) | ((hl & 0xfff) + (v & 0xfff) > 0xfff ? FH : 0) | (r > 0xffff ? FC : 0);
    this.hl = r & 0xffff;
  }

  /** SP + signed imm8 (ADD SP,e / LD HL,SP+e). H/C from unsigned low-byte math. */
  addSPe(): number {
    const raw = this.fetch8();
    const e = (raw << 24) >> 24;
    this.fl(false, false, (this.sp & 0xf) + (raw & 0xf) > 0xf, (this.sp & 0xff) + (raw & 0xff) > 0xff);
    return (this.sp + e) & 0xffff;
  }

  daa(): void {
    let a = this.a;
    if (this.f & FN) {
      if (this.f & FC) a = (a - 0x60) & 0xff;
      if (this.f & FH) a = (a - 0x06) & 0xff;
    } else {
      if ((this.f & FC) || a > 0x99) { a = (a + 0x60) & 0xff; this.f |= FC; }
      if ((this.f & FH) || (a & 0xf) > 0x09) a = (a + 0x06) & 0xff;
    }
    this.a = a;
    this.f = (this.f & (FN | FC)) | (a === 0 ? FZ : 0);
  }

  // ---- rotates / shifts (also used by the CB table) ----------------------

  rlc(v: number): number { const r = ((v << 1) | (v >>> 7)) & 0xff; this.fl(r === 0, false, false, (v & 0x80) !== 0); return r; }
  rrc(v: number): number { const r = ((v >>> 1) | ((v & 1) << 7)) & 0xff; this.fl(r === 0, false, false, (v & 1) !== 0); return r; }
  rl(v: number): number { const r = ((v << 1) | this.cy) & 0xff; this.fl(r === 0, false, false, (v & 0x80) !== 0); return r; }
  rr(v: number): number { const r = ((v >>> 1) | (this.cy << 7)) & 0xff; this.fl(r === 0, false, false, (v & 1) !== 0); return r; }
  sla(v: number): number { const r = (v << 1) & 0xff; this.fl(r === 0, false, false, (v & 0x80) !== 0); return r; }
  sra(v: number): number { const r = ((v >>> 1) | (v & 0x80)) & 0xff; this.fl(r === 0, false, false, (v & 1) !== 0); return r; }
  swap(v: number): number { const r = ((v << 4) | (v >>> 4)) & 0xff; this.fl(r === 0, false, false, false); return r; }
  srl(v: number): number { const r = v >>> 1; this.fl(r === 0, false, false, (v & 1) !== 0); return r; }

  // ---- execution --------------------------------------------------------

  /** Execute one instruction (or service an interrupt); return T-cycles. */
  step(): number {
    const pending = this.bus.read8(0xff0f) & this.bus.read8(0xffff) & 0x1f;

    if (this.halted) {
      if (pending) this.halted = false; // wakes even with IME off
      else return 4;
    }

    if (this.ime && pending) return this.service(pending);

    const willEnable = this.imeScheduled;
    const op = this.fetch8();
    const handler = OPS[op];
    if (!handler) {
      throw new Error(
        `Illegal opcode 0x${op.toString(16).padStart(2, "0")} at ` +
        `0x${((this.pc - 1) & 0xffff).toString(16).padStart(4, "0")}`,
      );
    }
    const cycles = handler(this);
    // EI takes effect after the following instruction — unless that
    // instruction was DI (which clears imeScheduled).
    if (willEnable && this.imeScheduled) {
      this.ime = true;
      this.imeScheduled = false;
    }
    return cycles;
  }

  private service(pending: number): number {
    this.ime = false;
    const bit = pending & -pending; // lowest set bit = highest priority
    const idx = 31 - Math.clz32(bit);
    this.bus.write8(0xff0f, this.bus.read8(0xff0f) & ~bit);
    this.push16(this.pc);
    this.pc = 0x40 + (idx << 3);
    return 20;
  }
}

// ---- register accessor tables (index 0-7: B C D E H L (HL) A) ------------

const R8_GET: ((c: CPU) => number)[] = [
  c => c.b, c => c.c, c => c.d, c => c.e, c => c.h, c => c.l,
  c => c.bus.read8(c.hl), c => c.a,
];

const R8_SET: ((c: CPU, v: number) => void)[] = [
  (c, v) => { c.b = v; }, (c, v) => { c.c = v; }, (c, v) => { c.d = v; },
  (c, v) => { c.e = v; }, (c, v) => { c.h = v; }, (c, v) => { c.l = v; },
  (c, v) => c.bus.write8(c.hl, v), (c, v) => { c.a = v; },
];

// index 0-3: BC DE HL SP (most 16-bit ops) / BC DE HL AF (PUSH/POP)
const R16_GET: ((c: CPU) => number)[] = [c => c.bc, c => c.de, c => c.hl, c => c.sp];
const R16_SET: ((c: CPU, v: number) => void)[] = [
  (c, v) => { c.bc = v; }, (c, v) => { c.de = v; }, (c, v) => { c.hl = v; }, (c, v) => { c.sp = v; },
];
const R16S_GET: ((c: CPU) => number)[] = [c => c.bc, c => c.de, c => c.hl, c => c.af];
const R16S_SET: ((c: CPU, v: number) => void)[] = [
  (c, v) => { c.bc = v; }, (c, v) => { c.de = v; }, (c, v) => { c.hl = v; }, (c, v) => { c.af = v; },
];

// index 0-3: NZ Z NC C
const COND: ((c: CPU) => boolean)[] = [
  c => (c.f & FZ) === 0, c => (c.f & FZ) !== 0,
  c => (c.f & FC) === 0, c => (c.f & FC) !== 0,
];

// ---- base opcode table ---------------------------------------------------
// Entries left undefined are the 11 illegal opcodes (D3 DB DD E3 E4 EB EC ED
// F4 FC FD) — step() throws on them, which doubles as a bug detector.

const OPS: (OpHandler | undefined)[] = new Array(256);

// 0x00-0x3F irregular block
OPS[0x00] = () => 4;                                                    // NOP
OPS[0x10] = c => { c.fetch8(); return 4; };                             // STOP (2 bytes; treated as NOP)
OPS[0x08] = c => { c.bus.write16(c.fetch16(), c.sp); return 20; };      // LD (nn), SP

OPS[0x07] = c => { c.a = c.rlc(c.a); c.f &= ~FZ; return 4; };           // RLCA
OPS[0x0f] = c => { c.a = c.rrc(c.a); c.f &= ~FZ; return 4; };           // RRCA
OPS[0x17] = c => { c.a = c.rl(c.a); c.f &= ~FZ; return 4; };            // RLA
OPS[0x1f] = c => { c.a = c.rr(c.a); c.f &= ~FZ; return 4; };            // RRA

OPS[0x27] = c => { c.daa(); return 4; };                                // DAA
OPS[0x2f] = c => { c.a ^= 0xff; c.f |= FN | FH; return 4; };            // CPL
OPS[0x37] = c => { c.f = (c.f & FZ) | FC; return 4; };                  // SCF
OPS[0x3f] = c => { c.f = (c.f & FZ) | ((c.f & FC) ^ FC); return 4; };   // CCF

OPS[0x02] = c => { c.bus.write8(c.bc, c.a); return 8; };                // LD (BC), A
OPS[0x12] = c => { c.bus.write8(c.de, c.a); return 8; };                // LD (DE), A
OPS[0x22] = c => { c.bus.write8(c.hl, c.a); c.hl = (c.hl + 1) & 0xffff; return 8; }; // LD (HL+), A
OPS[0x32] = c => { c.bus.write8(c.hl, c.a); c.hl = (c.hl - 1) & 0xffff; return 8; }; // LD (HL-), A
OPS[0x0a] = c => { c.a = c.bus.read8(c.bc); return 8; };                // LD A, (BC)
OPS[0x1a] = c => { c.a = c.bus.read8(c.de); return 8; };                // LD A, (DE)
OPS[0x2a] = c => { c.a = c.bus.read8(c.hl); c.hl = (c.hl + 1) & 0xffff; return 8; }; // LD A, (HL+)
OPS[0x3a] = c => { c.a = c.bus.read8(c.hl); c.hl = (c.hl - 1) & 0xffff; return 8; }; // LD A, (HL-)

OPS[0x18] = c => {                                                      // JR e
  const e = (c.fetch8() << 24) >> 24;
  c.pc = (c.pc + e) & 0xffff;
  return 12;
};

for (let i = 0; i < 4; i++) {
  OPS[0x20 + i * 8] = c => {                                            // JR cc, e
    const e = (c.fetch8() << 24) >> 24;
    if (!COND[i](c)) return 8;
    c.pc = (c.pc + e) & 0xffff;
    return 12;
  };
  OPS[0x01 + i * 16] = c => { R16_SET[i](c, c.fetch16()); return 12; }; // LD rr, nn
  OPS[0x03 + i * 16] = c => { R16_SET[i](c, (R16_GET[i](c) + 1) & 0xffff); return 8; }; // INC rr
  OPS[0x0b + i * 16] = c => { R16_SET[i](c, (R16_GET[i](c) - 1) & 0xffff); return 8; }; // DEC rr
  OPS[0x09 + i * 16] = c => { c.addHL(R16_GET[i](c)); return 8; };      // ADD HL, rr
}

for (let r = 0; r < 8; r++) {
  const mem = r === 6;
  OPS[r * 8 + 4] = c => { R8_SET[r](c, c.inc8(R8_GET[r](c))); return mem ? 12 : 4; }; // INC r
  OPS[r * 8 + 5] = c => { R8_SET[r](c, c.dec8(R8_GET[r](c))); return mem ? 12 : 4; }; // DEC r
  OPS[r * 8 + 6] = c => { R8_SET[r](c, c.fetch8()); return mem ? 12 : 8; };           // LD r, n
}

// 0x40-0x7F: LD r, r' (0x76 = HALT)
for (let i = 0x40; i < 0x80; i++) {
  if (i === 0x76) continue;
  const dst = (i >> 3) & 7;
  const src = i & 7;
  OPS[i] = c => { R8_SET[dst](c, R8_GET[src](c)); return dst === 6 || src === 6 ? 8 : 4; };
}
OPS[0x76] = c => { c.halted = true; return 4; }; // TODO: HALT bug (IME=0 + pending)

// 0x80-0xBF: ALU A, r — and the 0xC6+8n immediate forms
const ALU: ((c: CPU, v: number) => void)[] = [
  (c, v) => c.add8(v, 0),    // ADD
  (c, v) => c.add8(v, c.cy), // ADC
  (c, v) => c.sub8(v, 0),    // SUB
  (c, v) => c.sub8(v, c.cy), // SBC
  (c, v) => c.and8(v),       // AND
  (c, v) => c.xor8(v),       // XOR
  (c, v) => c.or8(v),        // OR
  (c, v) => c.cp8(v),        // CP
];
for (let i = 0; i < 64; i++) {
  const op = i >> 3;
  const src = i & 7;
  OPS[0x80 + i] = c => { ALU[op](c, R8_GET[src](c)); return src === 6 ? 8 : 4; };
}
for (let op = 0; op < 8; op++) {
  OPS[0xc6 + op * 8] = c => { ALU[op](c, c.fetch8()); return 8; };
}

// 0xC0-0xFF: control flow, stack, misc
for (let i = 0; i < 4; i++) {
  OPS[0xc0 + i * 8] = c => { if (!COND[i](c)) return 8; c.pc = c.pop16(); return 20; };  // RET cc
  OPS[0xc2 + i * 8] = c => { const t = c.fetch16(); if (!COND[i](c)) return 12; c.pc = t; return 16; }; // JP cc
  OPS[0xc4 + i * 8] = c => { const t = c.fetch16(); if (!COND[i](c)) return 12; c.push16(c.pc); c.pc = t; return 24; }; // CALL cc
  OPS[0xc1 + i * 16] = c => { R16S_SET[i](c, c.pop16()); return 12; };  // POP rr
  OPS[0xc5 + i * 16] = c => { c.push16(R16S_GET[i](c)); return 16; };   // PUSH rr
}
for (let i = 0; i < 8; i++) {
  OPS[0xc7 + i * 8] = c => { c.push16(c.pc); c.pc = i * 8; return 16; }; // RST
}

OPS[0xc3] = c => { c.pc = c.fetch16(); return 16; };                    // JP nn
OPS[0xc9] = c => { c.pc = c.pop16(); return 16; };                      // RET
OPS[0xcd] = c => { const t = c.fetch16(); c.push16(c.pc); c.pc = t; return 24; }; // CALL nn
OPS[0xd9] = c => { c.pc = c.pop16(); c.ime = true; return 16; };        // RETI (no EI delay)

OPS[0xe0] = c => { c.bus.write8(0xff00 + c.fetch8(), c.a); return 12; }; // LDH (n), A
OPS[0xf0] = c => { c.a = c.bus.read8(0xff00 + c.fetch8()); return 12; }; // LDH A, (n)
OPS[0xe2] = c => { c.bus.write8(0xff00 + c.c, c.a); return 8; };        // LD (C), A
OPS[0xf2] = c => { c.a = c.bus.read8(0xff00 + c.c); return 8; };        // LD A, (C)
OPS[0xea] = c => { c.bus.write8(c.fetch16(), c.a); return 16; };        // LD (nn), A
OPS[0xfa] = c => { c.a = c.bus.read8(c.fetch16()); return 16; };        // LD A, (nn)

OPS[0xe8] = c => { c.sp = c.addSPe(); return 16; };                     // ADD SP, e
OPS[0xf8] = c => { c.hl = c.addSPe(); return 12; };                     // LD HL, SP+e
OPS[0xe9] = c => { c.pc = c.hl; return 4; };                            // JP HL
OPS[0xf9] = c => { c.sp = c.hl; return 8; };                            // LD SP, HL

OPS[0xf3] = c => { c.ime = false; c.imeScheduled = false; return 4; };  // DI
OPS[0xfb] = c => { c.imeScheduled = true; return 4; };                  // EI

// ---- CB-prefixed table ---------------------------------------------------

const CB: OpHandler[] = new Array(256);
OPS[0xcb] = c => CB[c.fetch8()](c);

const ROT: ((c: CPU, v: number) => number)[] = [
  (c, v) => c.rlc(v), (c, v) => c.rrc(v), (c, v) => c.rl(v), (c, v) => c.rr(v),
  (c, v) => c.sla(v), (c, v) => c.sra(v), (c, v) => c.swap(v), (c, v) => c.srl(v),
];

for (let i = 0; i < 256; i++) {
  const r = i & 7;
  const n = (i >> 3) & 7; // rotate kind, or bit number
  const mem = r === 6;
  if (i < 0x40) {
    CB[i] = c => { R8_SET[r](c, ROT[n](c, R8_GET[r](c))); return mem ? 16 : 8; };
  } else if (i < 0x80) { // BIT n, r — C preserved
    CB[i] = c => { c.flZNH((R8_GET[r](c) & (1 << n)) === 0, false, true); return mem ? 12 : 8; };
  } else if (i < 0xc0) { // RES n, r
    CB[i] = c => { R8_SET[r](c, R8_GET[r](c) & ~(1 << n)); return mem ? 16 : 8; };
  } else {               // SET n, r
    CB[i] = c => { R8_SET[r](c, R8_GET[r](c) | (1 << n)); return mem ? 16 : 8; };
  }
}
